CREATE table NETFLIX(
show_id  VARCHAR(500),
type VARCHAR(500),
title VARCHAR(500),
director VARCHAR(500),
country VARCHAR(500),
date_added VARCHAR(5),
release_year INT,
rating VARCHAR(250),
duration VARCHAR(250),
listed_in VARCHAR(250)
);


select COUNT(*) AS TOTAL_COUNT from NETFLIX;

SELECT DISTINCT TYPE FROM NETFLIX;

--COUNT NUMBER OF MOVIES VS TV SHOWS

select TYPE, count(*) AS TOTAL_COUNT from NETFLIX GROUP BY TYPE;

--MOST COMMON RATING FOR MOVIES AND TV SHOWS

SELECT TYPE, RATING FROM
(
SELECT TYPE, RATING,COUNT(*),
RANK() OVER (PARTITION BY TYPE ORDER BY COUNT(*) DESC)  AS RANKING
FROM NETFLIX
GROUP BY 1,2
) AS T1 
WHERE
RANKING =1;

--LIST ALL MOVIES RELEASED IN A SPECIFIC YEAR
SELECT  * FROM NETFLIX WHERE
TYPE= 'MOVIE' AND release_year


SELECT COUNT(*) AS MM,release_year FROM NETFLIX GROUP BY RELEASE_YEAR ORDER BY 1;

SELECT DISTINCT (TYPE, RELEASE_YEAR) FROM NETFLIX ORDER BY 1;

SELECT TYPE,RELEASE_YEAR FROM NETFLIX;

SELECT
    release_year,
    type,
    COUNT(*) AS show_count
FROM
    NETFLIX
WHERE
    release_year =2021
GROUP BY
    release_year, type
ORDER BY
    release_year, type;

--find top 5 countries with most content on netflix

select 
UNNEST(STRING_TO_ARRAY(COUNTRY,',')) AS NEW_COUNTRY,
COUNT(SHOW_ID) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 5



--IDENTIFY THE LONGEST MOVIE

SELECT * FROM NETFLIX 
WHERE 
TYPE='MOVIE'
AND 
DURATION =(SELECT MAX(DURATION) FROM NETFLIX);

--FIND CONTENT ADDED IN THE LAST 5 YEARS

SELECT * FROM NETFLIX WHERE TO_DATE(DATE_ADDED, ' MONTH DD,YYYY') > CURRENT_DATE - INTERVAL '5 YEARS'


--FIND ALL THE MOVIES/TV SHOWS BY DIRECTOR 'George Ford'

SELECT TYPE FROM NETFLIX WHERE DIRECTOR ILIKE  '%George Ford%';


-- LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS
   --SPLIT_PART( DURATION, '', 1) AS SESSIONS 
SELECT *  FROM NETFLIX 
WHERE 
TYPE = 'TV Show'
AND 
CAST(SPLIT_PART(DURATION, '', 1) AS INTEGER) > 5 

select distinct duration from netflix;

--COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE

SELECT LISTED_IN, COUNT(SHOW_ID) AS TOTAL_CONTENT, UNNEST(STRING_TO_ARRAY(LISTED_IN,',')) AS GENRE FROM NETFLIX GROUP BY 1

--FIND EACH YEAR AND AVERAGE NUMBER OF CONTENTS RELEASE BY INDIA ON NETFLIX. RETURN TOP 5 YEAR BY HIGHEST CONTENT RELEASE?

SELECT extract( year from TO_DATE(DATE_ADDED, 'Month DD, YYYY')) AS year, 
count(*) as yearly_content,
ROUND(count(*)::NUMERIC/(select count(*) FROM NETFLIX WHERE COUNTRY ='PAKISTAN')::NUMERIC * 100,2) as avg_content
from netflix
WHERE COUNTRY ='PAKISTAN'
group by 1;



--LIST ALL MOVIES THAT ARE DOCUMENTARIES

SELECT * FROM NETFLIX WHERE LISTED_IN ILIKE '%documentaries%';

--FIND ALL CONTENT WITHOUT A DIRECTOR


SELECT * FROM NETFLIX WHERE  DIRECTOR IS NULL;


-- FIND HOW MANY MOVIES DIRECTOR 'DANIEL' APPEARED IN LAST 10  YEARS!

SELECT * FROM NETFLIX 
WHERE DIRECTOR ILIKE '%DANIEL%' 
AND
RELEASE_YEAR > EXTRACT(YEAR FROM CURRENT_DATE) - 10

--FIND THE TOP 10 DIRECTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED IN CANADA?

SELECT  UNNEST(STRING_TO_ARRAY(DIRECTOR,',') ) AS DIRECTORS, COUNT(*) AS TOATL_CONTENT  FROM NETFLIX  WHERE COUNTRY ILIKE '%CANADA%' GROUP BY 1 ORDER BY 2 DESC LIMIT 10;



